# version 3+ does different things re: networking from 2.x
# mainly things to support swarms
# aka things we don't need/want
version: '2.4'
services:
  # httpd
  danger-web:
    image: docker.io/nginx:1.23-alpine
    container_name: danger-web
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wwwroot:/var/www
    # normally behind centeral traefik defined in production-manifests/services/traefik
    ports:
      - "127.0.0.1:80:80"
    # join danger-internal network
    networks:
      danger-internal: {}

  # php-fpm
  danger-php:
    # production: track "prod" tag on ghcr.io
    # image: ghcr.io/wetfish/danger:prod
    # for development, build the image
    # TODO: once ghcr.io autobuilds in place, change this
    build: .
    container_name: danger-php
    restart: unless-stopped
    # db connection info
    env_file:
      - ./php.env
    volumes:
      - ./wwwroot:/var/www
    networks:
      danger-internal: {}

  # database
  danger-db:
    image: docker.io/mariadb:10.10
    container_name: danger-db
    restart: unless-stopped
    env_file:
      - ./mariadb.env
    # built-in healthcheck script
    healthcheck:
      test: ["healthcheck.sh", "--su=mysql", "--connect", "--innodb_initialized"]
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./db/data:/var/lib/mysql
    networks:
      danger-internal: {}

networks:
  # ephemeral, created for us by compose
  danger-internal:
    driver: bridge
