# version 3+ does different things re: networking from 2.x
# mainly things to support swarms
# aka things we don't need/want
version: '2.4'
services:
  # httpd
  danger-web:
    image: ghcr.io/wetfish/danger:dev-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: danger-web
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wwwroot:/var/www:ro
    # normally behind centeral traefik defined in production-manifests/services/traefik
    ports:
      - "127.0.0.1:2402:80"
    # join danger-internal network
    networks:
      danger-internal: {}

  # php-fpm
  danger-php:
    # for development, build the image
    image: ghcr.io/wetfish/danger:dev-php
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: danger-php
    restart: unless-stopped
    # db connection info
    env_file:
      - ./php.env
    volumes:
      - ./config/php-fpm.conf:/etc/php/5.6/fpm/php-fpm.conf:ro
      - ./config/php-fpm-pool.conf:/etc/php/5.6/fpm/pool.d/www.conf:ro
      - ./config/php.ini:/etc/php/5.6/fpm/php.ini:ro
      - ./wwwroot:/var/www:ro
    networks:
      danger-internal: {}

  # database
  danger-db:
    image: docker.io/mariadb:10.10
    container_name: danger-db
    restart: unless-stopped
    env_file:
      - ./mariadb.env
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/setup.sql:ro
      - ./db/data:/var/lib/mysql:rw
    networks:
      danger-internal: {}

networks:
  # ephemeral, created for us by compose
  danger-internal:
    driver: bridge
