# version 3+ does different things re: networking from 2.x
# mainly things to support swarms
# aka things we don't need/want
version: '2.4'
services:
  # httpd
  danger-web:
    image: ghcr.io/wetfish/danger:prod-nginx
    container_name: danger-web
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    # join danger-internal and traefik-backend networks
    networks:
      danger-internal: {}
      traefik-backend: {}

  # php-fpm
  danger-php:
    # production: track "prod" tag on ghcr.io
    image: ghcr.io/wetfish/danger:prod-php
    container_name: danger-php
    restart: unless-stopped
    # db connection info
    env_file:
      - ./php.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./config/php-fpm.conf:/etc/php/5.6/fpm/php-fpm.conf:ro
      - ./config/php-fpm-pool.conf:/etc/php/5.6/fpm/pool.d/www.conf:ro
      - ./config/php.ini:/etc/php/5.6/fpm/php.ini:ro
    networks:
      danger-internal: {}

  # database
  danger-db:
    image: docker.io/mariadb:10.10
    container_name: danger-db
    restart: unless-stopped
    env_file:
      - ./mariadb.env
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/setup.sql:ro
      - ./db/data:/var/lib/mysql:rw
    networks:
      danger-internal: {}

  # watchtower - automatically pull new container images
  # note: this does not update the repo
  # if deployment files have changed you will need to git pull && docker compose up -d manually
  danger-watchtower:
    image: ghcr.io/containrrr/watchtower:1.5.3
    container_name: danger-watchtower
    environment:
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_POLL_INTERVAL=30"
      - "WATCHTOWER_LABEL_ENABLE=true"
      - "NO_COLOR=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  # ephemeral, created for us by compose
  danger-internal:
    driver: bridge
  # persistent, externally created
  traefik-backend:
    external: true
